name: C++ Build Action  

on:  
  push: 
    branches: [ main ]  
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3

      # Ensure g++ is available (usually already installed on Linux runners) 
      - name: Install g++ (if needed)
        if: ${{ runner.os != 'Linux' }}  # Install if NOT on a Linux environment
        run: sudo apt-get install g++

      - name: Build with g++ 
        run: g++ 2048.cpp -o 2048
